/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32l476xx.h"

/*************************************************
* function declarations
*************************************************/
void set_sysclk_to_msi_8MHz(void);
void set_sysclk_to_msi_16MHz(void);

int main(void);
void delay(volatile uint32_t s);

void set_sysclk_to_msi_8MHz(void)
{
	RCC->CR |= (1 << 0);	//Enable MSI (bit 0)
	while(!(RCC->CR & (1 << 1)));	//Wait until MSI is ready (bit 1)

	FLASH->ACR = (1 << 8) | (1 << 9) | (1 << 10 ) | (0 << 0); //Configurate FLASH memory for the given clock frequency

	RCC->CR &= 0xFFFFFF0F;	//Clear bits 7:4 for MSIRANGE
	RCC->CR |= 0x00000070;  //Write 0111 to MSIRANGE
	RCC->CR |= (1 << 3);	//Configure MSIRANGE with RCC_CR register

	RCC->CFGR &= 0xFFFFFFFC;	//Clear bits 1:0
	RCC->CFGR |= 0x00000000;	//Write 00 to bits 1:0 to select MSI as system clock
	while (!(RCC->CFGR & (0 << 2)));	//Wait until MSI is selected as system clock (bits 3:2)
}

void set_sysclk_to_msi_16MHz(void)
{
	RCC->CR |= (1 << 0);	//Enable MSI (bit 0)
	while(!(RCC->CR & (1 << 1)));	//Wait until MSI is ready (bit 1)
  
  FLASH->ACR = (1 << 8) | (1 << 9) | (1 << 10 ) | (0 << 0); //Configurate FLASH memory for the given clock frequency

	RCC->CR &= 0xFFFFFF0F;	//Clear bits 7:4 for MSIRANGE
	RCC->CR |= 0x00000080;  //Write 1000 to MSIRANGE
	RCC->CR |= (1 << 3);	//Configure MSIRANGE with RCC_CR register

	RCC->CFGR &= 0xFFFFFFFC;	//Clear bits 1:0
	RCC->CFGR |= 0x00000000;	//Write 00 to bits 1:0 to select MSI as system clock
	while (!(RCC->CFGR & (0 << 2)));	//Wait until MSI is selected as system clock (bits 3:2)
}

int main(void)
{
	set_sysclk_to_msi_8MHz(); //Set sysclk frequency to 8MHz

	// Enable GPIOA Peripheral Clock (bit 0 in AHB2ENR register)
	RCC->AHB2ENR = 0x00000001;

	// Make GPIOA Pin5 as output pin (bits 1:0 in MODER register)
	GPIOA->MODER &= 0xFFFFF3FF;		// Clear bits 11, 10 for P5
	GPIOA->MODER |= 0x00000400;		// Write 01 to bits 11, 10 for P5

	while(1)
	{
		GPIOA->ODR |= 0x0020;			// write 1 to pin 5 (LED ON)
		delay(500000);
		GPIOA->ODR &= 0x0000; //LED OFF
		delay(500000);
		
	}

	__asm__("NOP"); // Assembly inline can be used if needed
	return 0;
}

// A simple and not accurate delay function
void delay(volatile uint32_t s)
{
    for(s; s>0; s--){
        // Do nothing
    }
}

